# -*- coding: utf-8 -*-
"""app_stroke.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Q7gkf-7W7ozsyR8IXgzQLIx4UvU9Mv_
"""

import streamlit as st
import pandas as pd
import joblib

# Memuat model pipeline yang sudah dilatih
model = joblib.load("stroke_ann_pipeline.pkl")

st.title("🧠 Sistem Penunjang Keputusan Prediksi Stroke")

st.markdown("Masukkan data pasien pada form berikut, lalu klik **Prediksi**.")

# --- Input fitur dengan slider dan dropdown ---

# Umur
age = st.slider("Umur", min_value=0, max_value=100, value=45)

# Jenis kelamin (sesuaikan dengan kategori di dataset: 'Male', 'Female', 'Other')
gender = st.selectbox("Jenis Kelamin", ["Male", "Female", "Other"])

# Hipertensi (0 = tidak, 1 = ya)
hypertension_label = st.selectbox("Hipertensi", ["Tidak", "Ya"])
hypertension = 1 if hypertension_label == "Ya" else 0

# Penyakit jantung (0 = tidak, 1 = ya)
heart_label = st.selectbox("Penyakit Jantung", ["Tidak", "Ya"])
heart_disease = 1 if heart_label == "Ya" else 0

# Pernah menikah
ever_married = st.selectbox("Status Pernikahan", ["Yes", "No"])

# Tipe pekerjaan (sesuai dataset)
work_type = st.selectbox(
    "Jenis Pekerjaan",
    ["Private", "Self-employed", "Govt_job", "children", "Never_worked"]
)

# Tipe tempat tinggal
Residence_type = st.selectbox(
    "Tipe Tempat Tinggal",
    ["Urban", "Rural"]
)

# Rata-rata kadar glukosa
avg_glucose_level = st.slider(
    "Rata-rata Kadar Glukosa",
    min_value=50.0, max_value=300.0, value=120.0
)

# BMI
bmi = st.slider(
    "BMI (Body Mass Index)",
    min_value=10.0, max_value=60.0, value=25.0
)

# Status merokok (sesuai dataset)
smoking_status = st.selectbox(
    "Status Merokok",
    ["formerly smoked", "never smoked", "smokes", "Unknown"]
)

# Tombol prediksi
if st.button("Prediksi Risiko Stroke"):
    # Menyusun data input ke dalam DataFrame satu baris
    input_dict = {
        "gender": [gender],
        "age": [age],
        "hypertension": [hypertension],
        "heart_disease": [heart_disease],
        "ever_married": [ever_married],
        "work_type": [work_type],
        "Residence_type": [Residence_type],
        "avg_glucose_level": [avg_glucose_level],
        "bmi": [bmi],
        "smoking_status": [smoking_status],
    }

    input_df = pd.DataFrame(input_dict)

    # Menggunakan model pipeline untuk prediksi
    pred = model.predict(input_df)[0]
    proba = model.predict_proba(input_df)[0, 1]

    st.subheader("Hasil Prediksi")

    if pred == 1:
        st.error(f"⚠️ Pasien **BERISIKO STROKE**.\n\nProbabilitas stroke: **{proba:.2%}**")
    else:
        st.success(f"✅ Pasien **TIDAK BERISIKO STROKE** (menurut model).\n\nProbabilitas stroke: **{proba:.2%}**")

    st.caption("Catatan: Ini hanya model pembelajaran mesin sebagai contoh akademik, "
               "bukan pengganti diagnosa dokter.")